Browser:
    Chrome: Chrome
Qentinelqi:
    URL: https://qentinelqi.github.io/shop/
    Text: Find your spirit animal
    TshirtName: Gerald the Giraffe
    TshirtPrice: $9.00
    AddCart: Add to cart
    Cartsummary: Cart summary